In [1]:
import numpy as np

# Creating Arrays

In [74]:
mylist = [1,2,3]
x = np.array(mylist)
x

array([1, 2, 3])

In [75]:
y = np.array([4,5,6])
y

array([4, 5, 6])

In [76]:
m = np.array([[7,8,9], [10,11,12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [77]:
m.shape

(2, 3)

In [78]:
n = np.arange(0, 30, 2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [79]:
n = n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [80]:
o = np.linspace(0,4,9)
o

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [9]:
o.resize(3,3)
o

array([[ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ]])

In [10]:
np.ones((3,2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [11]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [12]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [13]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [14]:
np.array([1,2,3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [15]:
np.repeat([1,2,3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [16]:
p = np.ones([2,3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [17]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [18]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

# Operations

In [19]:
x + y

array([5, 7, 9])

In [20]:
x * y

array([ 4, 10, 18])

In [21]:
x**2

array([1, 4, 9])

In [22]:
x.dot(y)

32

In [23]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [24]:
z.shape

(2, 3)

In [25]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [26]:
z.dtype

dtype('int64')

In [27]:
z = z.astype('f')
z.dtype

dtype('float32')

In [28]:
a = np.array([-4, -2, 1, 3, 5])

In [29]:
a.sum()

3

In [30]:
a.max()

5

In [31]:
a.min()

-4

In [32]:
a.mean()

0.59999999999999998

In [33]:
a.std()

3.2619012860600183

In [34]:
# inedx of the max value
a.argmax()

4

In [35]:
a.argmin()

0

# Indexing / Slicing

In [36]:
s = np.arange(13)**2

In [37]:
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [38]:
s[0], s[4], s[0:3]

(0, 16, array([0, 1, 4]))

In [39]:
s[1:5]

array([ 1,  4,  9, 16])

In [40]:
s[-4:]

array([ 81, 100, 121, 144])

In [41]:
s[-5::-2]

array([64, 36, 16,  4,  0])

In [42]:
r = np.arange(36)
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [43]:
r[2,2]

14

In [44]:
r[3, 3:6]

array([21, 22, 23])

In [45]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [46]:
r[-1, ::2]

array([30, 32, 34])

In [47]:
r[r > 30]

array([31, 32, 33, 34, 35])

In [48]:
r[r > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35])

In [49]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [50]:
r2 = r[:3, :3]

In [51]:
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [52]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [53]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [54]:
# Notice how a copy was not made
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [55]:
r_copy[:] = 10

In [56]:
r_copy

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [57]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

# Iterating over arrays

In [58]:
test = np.random.randint(0,10,(4,3))
test

array([[0, 5, 3],
       [3, 2, 8],
       [5, 3, 9],
       [6, 1, 3]])

In [59]:
for row in test:
    print(row)

[0 5 3]
[3 2 8]
[5 3 9]
[6 1 3]


In [60]:
for i in range(len(test)):
    print(test[i])

[0 5 3]
[3 2 8]
[5 3 9]
[6 1 3]


In [61]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [0 5 3]
row 1 is [3 2 8]
row 2 is [5 3 9]
row 3 is [6 1 3]


In [62]:
test2 = test**2
test2

array([[ 0, 25,  9],
       [ 9,  4, 64],
       [25,  9, 81],
       [36,  1,  9]])

In [63]:
for i, j in zip(test, test2):
    print(i, '+', j, '=', i + j)

[0 5 3] + [ 0 25  9] = [ 0 30 12]
[3 2 8] + [ 9  4 64] = [12  6 72]
[5 3 9] + [25  9 81] = [30 12 90]
[6 1 3] + [36  1  9] = [42  2 12]


In [64]:
z = np.arange(36)
z.resize((6,6))
z

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [65]:
z.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

In [66]:
z

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [67]:
z[[-2,-1],[-2,-1]] # This returns the z[-2,-2] and z[-1,-1]
z[[-2,-1],[-2,-1]] == [z[-2,-2],z[-1,-1]]
z[range(0,6),range(0,6)]

array([ 0,  7, 14, 21, 28, 35])

In [68]:
z[2::2,2::2]

array([[14, 16],
       [26, 28]])

In [69]:
z[2:4,2:4]

array([[14, 15],
       [20, 21]])

In [70]:
z[::2,::2]

array([[ 0,  2,  4],
       [12, 14, 16],
       [24, 26, 28]])

In [71]:
for x in zip([1,2],[1,2]):
    print(x)

(1, 1)
(2, 2)


In [72]:
z[...]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])