In [1]:
import numpy as np

# Creating Arrays

In [2]:
mylist = [1,2,3]
x = np.array(mylist)
x

array([1, 2, 3])

In [3]:
y = np.array([4,5,6])
y

array([4, 5, 6])

In [4]:
m = np.array([[7,8,9], [10,11,12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [5]:
m.shape

(2, 3)

In [7]:
n = np.arange(0, 30, 2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [8]:
n = n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [11]:
o = np.linspace(0,4,9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [12]:
o.resize(3,3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [14]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [18]:
np.array([1,2,3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [19]:
np.repeat([1,2,3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [20]:
p = np.ones([2,3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [22]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [23]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

# Operations

In [24]:
x + y

array([5, 7, 9])

In [25]:
x * y

array([ 4, 10, 18])

In [26]:
x**2

array([1, 4, 9])

In [27]:
x.dot(y)

32

In [29]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [30]:
z.shape

(2, 3)

In [31]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [32]:
z.dtype

dtype('int64')

In [33]:
z = z.astype('f')
z.dtype

dtype('float32')

In [34]:
a = np.array([-4, -2, 1, 3, 5])

In [35]:
a.sum()

3

In [36]:
a.max()

5

In [37]:
a.min()

-4

In [38]:
a.mean()

0.6

In [39]:
a.std()

3.2619012860600183

In [42]:
# inedx of the max value
a.argmax()

4

In [43]:
a.argmin()

0

# Indexing / Slicing

In [44]:
s = np.arange(13)**2

In [45]:
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [46]:
s[0], s[4], s[0:3]

(0, 16, array([0, 1, 4]))

In [47]:
s[1:5]

array([ 1,  4,  9, 16])

In [48]:
s[-4:]

array([ 81, 100, 121, 144])

In [49]:
s[-5::-2]

array([64, 36, 16,  4,  0])

In [50]:
r = np.arange(36)
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [51]:
r[2,2]

14

In [52]:
r[3, 3:6]

array([21, 22, 23])

In [53]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [54]:
r[-1, ::2]

array([30, 32, 34])

In [55]:
r[r > 30]

array([31, 32, 33, 34, 35])

In [56]:
r[r > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35])

In [57]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [58]:
r2 = r[:3, :3]

In [59]:
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [60]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [61]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [62]:
# Notice how a copy was not made
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [63]:
r_copy[:] = 10

In [64]:
r_copy

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [65]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

# Iterating over arrays

In [66]:
test = np.random.randint(0,10,(4,3))
test

array([[6, 3, 4],
       [6, 9, 7],
       [5, 9, 0],
       [6, 0, 0]])

In [67]:
for row in test:
    print(row)

[6 3 4]
[6 9 7]
[5 9 0]
[6 0 0]


In [68]:
for i in range(len(test)):
    print(test[i])

[6 3 4]
[6 9 7]
[5 9 0]
[6 0 0]


In [69]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [6 3 4]
row 1 is [6 9 7]
row 2 is [5 9 0]
row 3 is [6 0 0]


In [70]:
test2 = test**2
test2

array([[36,  9, 16],
       [36, 81, 49],
       [25, 81,  0],
       [36,  0,  0]])

In [71]:
for i, j in zip(test, test2):
    print(i, '+', j, '=', i + j)

[6 3 4] + [36  9 16] = [42 12 20]
[6 9 7] + [36 81 49] = [42 90 56]
[5 9 0] + [25 81  0] = [30 90  0]
[6 0 0] + [36  0  0] = [42  0  0]


In [74]:
z = np.arange(36)
z.resize((6,6))
z

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [75]:
z.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

In [76]:
z

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [97]:
z[[-2,-1],[-2,-1]] # This returns the z[-2,-2] and z[-1,-1]
z[[-2,-1],[-2,-1]] == [z[-2,-2],z[-1,-1]]
z[range(0,6),range(0,6)]

array([ 0,  7, 14, 21, 28, 35])

In [78]:
z[2::2,2::2]

array([[14, 16],
       [26, 28]])

In [79]:
z[2:4,2:4]

array([[14, 15],
       [20, 21]])

In [80]:
z[::2,::2]

array([[ 0,  2,  4],
       [12, 14, 16],
       [24, 26, 28]])

In [102]:
for x in zip([1,2],[1,2]):
    print(x)

(1, 1)
(2, 2)


In [107]:
z[...]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])